version: v1
services:
  - type: web
    name: ticketflow-app
    env: python
    plan: free
    branch: main
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18
